info:
  namespace: customcrops
items:
  pot:
    display_name: display-name-dry_pot
    resource:
      material: PAPER
      generate: false
      model_path: 'item/basics/dry_pot'
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
        break_tools_whitelist:
        - AXE
  watered_pot:
    display_name: display-name-wet_pot
    resource:
      material: PAPER
      generate: false
      model_path: 'item/basics/wet_pot'
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        cancel_drop: true
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
        break_tools_whitelist:
        - AXE
  crow_stand:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: item/basics/crow_stand
  crow_fly:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: item/basics/crow_fly
  scarecrow:
    display_name: display-name-scarecrow
    resource:
      generate: false
      material: PAPER
      model_path: item/basics/scarecrow
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: false
        hitbox:
          length: 1
          width: 1
          height: 2
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  greenhouse_glass:
    display_name: display-name-greenhouse_glass
    resource:
      material: PAPER
      generate: false
      model_path: 'item/basics/greenhouse_glass'
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: true
        cancel_drop: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: true
          ceiling: true
          floor: true
  crop_stage_death:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: 'item/basics/dead_crop'
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: false
        cancel_drop: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  soil_surveyor:
    display_name: display-name-soil_surveyor
    resource:
      generate: false
      material: PAPER
      model_path: 'item/basics/soil_surveyor'
loots:
  blocks:
    wet_pot:
      type: customcrops:watered_pot
      items:
        result_1:
          item: customcrops:pot
          min_amount: 1
          max_amount: 1
          chance: 100
          ignore_fortune: true
categories:
  customcrops_basics:
    enabled: true
    icon: customcrops:pot
    name: 'display-category-customcrops_basics'
    items:
      - customcrops:pot
      - customcrops:watered_pot
      - customcrops:crow_stand
      - customcrops:crow_fly
      - customcrops:greenhouse_glass
      - customcrops:crop_stage_death
      - customcrops:scarecrow
      - customcrops:soil_surveyor